# -*- coding: utf-8 -*-
"""Midterm for Data Bootcamp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFwCKVm8ZpFG_H-iTLsFago5S1lPmLpJ
"""

# install the packages we'll need
!pip install pybaseball pandas matplotlib seaborn

from pybaseball import batting_stats, cache
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# turn on caching so it doesn't reload data every time
cache.enable()
sns.set(style="whitegrid")

# 1. get batting data for a few seasons
# grabbing 2023–2025 so we can look at some multi-year averages
bat = batting_stats(2023, 2025)
print(f"Raw data shape: {bat.shape}")

# keep only the columns that are actually useful for hitting analysis
cols = ['Season','Name','Team','Age','OPS','wOBA','SLG','HR','Barrel%','HardHit%','WAR']
bat = bat[[c for c in cols if c in bat.columns]].dropna()
print(f"After filtering columns: {bat.shape}")

"""Player level analysis"""

# 2. average by player (combine seasons)
# some players show up in multiple years; take their numeric average
player_stats = bat.groupby("Name", as_index=False).mean(numeric_only=True)

# make column names cleaner
player_stats = player_stats.rename(columns=lambda x: x.strip().lower().replace('%','_pct'))

print("Player-level dataset sample:")
player_stats.head()

# 3. look at how player hitting relates to WAR
# OPS vs WAR — does hitting better actually mean more overall value?
plt.figure(figsize=(7,5))
sns.scatterplot(data=player_stats, x="ops", y="war")
plt.title("OPS vs WAR (Players, 2023–2025 avg)")
plt.xlabel("OPS")
plt.ylabel("WAR")
plt.show()

# wOBA vs WAR — another version of offensive value
plt.figure(figsize=(7,5))
sns.scatterplot(data=player_stats, x="woba", y="war")
plt.title("wOBA vs WAR (Players, 2023–2025 avg)")
plt.xlabel("wOBA")
plt.ylabel("WAR")
plt.show()

# check how the main hitting metrics move together
corr = player_stats[['ops','woba','slg','hr','barrel_pct','hardhit_pct','war']].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation among batting metrics and WAR (player level)")
plt.show()

"""team-level analysis"""

# 4. average by team (to see team-wide hitting trends)
# group all players by team and take mean values
team_stats = bat.groupby("Team", as_index=False).mean(numeric_only=True)
team_stats = team_stats.rename(columns=lambda x: x.strip().lower().replace('%','_pct'))

# create a "fake" win percentage just based on OPS strength
team_stats['fake_win_pct'] = team_stats['ops'] / team_stats['ops'].max()

print("Team-level dataset sample:")
team_stats.head()

# 5. see if team hitting connects to success (fake win%)
# -------------------------------------------------
plt.figure(figsize=(7,5))
sns.scatterplot(data=team_stats, x="ops", y="fake_win_pct")
plt.title("Team OPS vs 'Fake' Win Percentage (2023–2025 avg)")
plt.xlabel("Team OPS")
plt.ylabel("Fake Win Percentage")
plt.show()

# try with wOBA too
plt.figure(figsize=(7,5))
sns.scatterplot(data=team_stats, x="woba", y="fake_win_pct")
plt.title("Team wOBA vs 'Fake' Win Percentage (2023–2025 avg)")
plt.xlabel("Team wOBA")
plt.ylabel("Fake Win Percentage")
plt.show()

# check which hitting stats line up best with this fake win%
team_corr = team_stats[['ops','woba','slg','hr','barrel_pct','hardhit_pct','war','fake_win_pct']].corr()
plt.figure(figsize=(7,6))
sns.heatmap(team_corr, annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Correlation of team batting metrics with 'Fake' Win% (2023–2025 avg)")
plt.show()

# check which hitting stats line up best with this fake win%
team_corr = team_stats[['ops','woba','slg','hr','barrel_pct','hardhit_pct','war','fake_win_pct']].corr()
plt.figure(figsize=(7,6))
sns.heatmap(team_corr, annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Correlation of team batting metrics with 'Fake' Win% (2023–2025 avg)")
plt.show()

# 6. a quick summary
corr_ops_war = player_stats['ops'].corr(player_stats['war'])
corr_woba_war = player_stats['woba'].corr(player_stats['war'])
corr_ops_fake = team_stats['ops'].corr(team_stats['fake_win_pct'])
corr_woba_fake = team_stats['woba'].corr(team_stats['fake_win_pct'])

print("Top 5 hitters by WAR (multi-season average):")
display(player_stats[['name','war']].sort_values('war', ascending=False).head())

print(f"Correlation between OPS and WAR: {corr_ops_war:.3f}")
print(f"Correlation between wOBA and WAR: {corr_woba_war:.3f}")
print(f"Correlation between OPS and Fake Win%: {corr_ops_fake:.3f}")
print(f"Correlation between wOBA and Fake Win%: {corr_woba_fake:.3f}")